### PR TITLE
Upgrading phpunit, wow we're way behind

### PR DESCRIPTION
**Pull request by jpfuentes2**

### CODE REVIEW

**Comment by jpfuentes2** [comment]
If we want to upgrade to recent stable php-unit we'll have to configure travis CI to pair up the right versions of PHP x php-unit. Do we want the newest or bump up a major or two?

**Comment by Rican7** [comment]
Probably best to just upgrade to PHPUnit 4.x so we don't have to break compatibility with the currently supported PHP versions.

Just my 2¢.

**Comment by Rican7** [comment]
Awesome work. Thanks!

**Comment by koenpunt** [comment]
We probably want php 5.6 and 7.0 in the Travis config. Maybe for now with 7.0 allowing failures, but that gives the possibility of keeping track how far off we are.

**Pull request merged**
