### PR TITLE
Update for PHP 7 Array to string Exception

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jpfuentes2** [comment]
Can you provide a link to why this is necessary?

**Comment by dperrymorrow** [comment]
I have this same issue, without it any mass assignment of attributes throws an error in php 7.0.
```
php -v
PHP 7.0.0 (cli) (built: Dec  2 2015 13:06:23) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
```

```
$this->user->update_attributes($_POST['user'])
```
```
Undefined property: ContentPortal\User->Array in /home/dave/d.wikidiy.com/prod/extensions/wikihow/ext-utils/mvc/vendor/php-activerecord/php-activerecord/lib/Model.php on line 521
```

**Comment by jpfuentes2** [comment]
Thanks, @dperrymorrow. I saw yesterday that @wikihow forked this project and I see you're a member of the org. Is WikiHow using php-activerecord?

**Comment by dperrymorrow** [comment]
yes we are, as a previous Rails developer, i really enjoy using Active Record models in PHP. Thank you for this library.

We are upgrading to php 7 soon which is why I'm hitting this problem in my test suites under php 7

**Comment by jpfuentes2** [comment]
Awesome! That's cool news to know :) You're welcome, I hope it makes your life a bit easier :)

Okay, merging.

Thanks!

**Comment by dperrymorrow** [comment]
Great thanks! any plans on a release? looks like the last one was 2013. Or does everyone just use ```dev-master``` for composer installs?

**Comment by jpfuentes2** [comment]
I think everyone is using master for now. We had plans to make a release and some good work was done there but the efforts languished.

I'm interested in making another release but there's a lot of bug fixes/features to be listed in a `CHANGELOG` as well as documentation to improve. It's a non-trivial amount of work. I can't make any promises with my current workload, sorry :(

**Comment by koenpunt** [comment]
We should probably add php7 to the Travis configuration, now that we apparently are supporting it :)

**Pull request merged**
