### PR TITLE
fix eager loading caching

### PR DESCRIPTION
**Pull request by shmax**
Fix for https://github.com/jpfuentes2/php-activerecord/issues/467.

### CODE REVIEW

**Comment by koenpunt** [comment]
Thanks! Could you add a test for the faulty behavior as well. To prevent this issue to return in a later release.

**Comment by shmax** [comment]
Sure, will take a crack at it this evening.

**Comment by shmax** [comment]
Added test (with some difficulty).

**Comment by koenpunt** [comment]
Merged as 03a68be5828522109917c31208404a1fb41818a0

**Pull request closed without merging**
