### PR TITLE
Add support for PHP 7.1 DateTime::setTime with microseconds

### PR DESCRIPTION
**Pull request by hising**
- Added $microseconds with default set to 0 as argument
- Added test for making sure setTime with and without microseconds generate same output

### CODE REVIEW

**Comment by koenpunt** [comment]
Thanks, looks fine by me. Although the `.gitignore` entry should be in your global git ignore file, so if you can take that commit out

**Comment by koenpunt** [comment]
Or in `.git/info/exclude`, if you have other project where for some reason you want the `.idea` folder to be under source control

**Comment by IAkumaI** [comment]
Why still not merged?

**Comment by hising** [comment]
@IAkumaI I guess it is up to the maintainers to do check and merge. I haven't poked them, I see that there are more pull requests solving the same problem. A temporary solution could be to override the class in your local code I guess?

**Comment by IAkumaI** [comment]
@hising My temporary solutions is editing file in vendor directory. Hard and stupid, but works )

**Comment by shmax** [comment]
I've grabbed your fix in this fork, which is actively maintained:

https://github.com/php-activerecord/activerecord

You can grab it from packagist: `composer require php-patterns/activerecord`. New issues and PRs are welcome.

**Comment by hising** [comment]
@shmax Awesome! I'll have a look at your fork. Thanks.

**Pull request merged**
