### PR TITLE
Override additional DateTime methods

### PR DESCRIPTION
**Pull request by shaneiseminger**
The `ActiveRecord\DateTime` class does not always get flagged as dirty when it's modified. This is because the class doesn't override all of the `DateTime` methods that are capable of modifying its value. I've added overriding methods in this commit so that whenever the following are called, the value will get flagged as dirty:

`DateTime::add()`
`DateTime::sub()`
`DateTime::modify()`
`DateTime::setTimezone()`

### CODE REVIEW

**Comment by koenpunt** [comment]
I see we've used `call_user_func_array` for the methods before, but it actually would be better to explicitly call the functions.
Could you update that in your PR? And some tests would be great too. Thanks!

**Comment by koenpunt** [comment]
And the return value should be returned to support method chaining

**Comment by shaneiseminger** [comment]
Sure. Good point about the method chaining.

**Comment by koenpunt** [comment]
The bug that is occurring is because the default value for the `$day` argument for `setISODate` is set to `null`, whereas the parent has it set to `1`.
But this faulty behavior was masked because `func_get_args` apparently ignores default values.

If you can update that, and also the `$second=null` to `$second=0` for `setTime`, then we're golden :rocket:

**Comment by shaneiseminger** [comment]
Ah, thanks for spotting that -- fixed.

**Comment by koenpunt** [comment]
Thanks!

**Comment by shaneiseminger** [comment]
Thank you!

**Pull request merged**
