### PR TITLE
Cache exception

### PR DESCRIPTION
**Pull request by koenpunt**
The `CacheException` class was missing..

### CODE REVIEW

**Comment by Rican7** [comment]
... it was... missing?

wat

**Comment by Rican7** [comment]
LGTM 👍

**Comment by jpfuentes2** [comment]
:(( not even gonna git blame ...

**Comment by koenpunt** [comment]
@Rican7 next time just squash my commits when there's a `fixup! ...` amongst them. Or let me rebase before merge. That way we can avoid fixup commits :)

**Comment by koenpunt** [comment]
Especially when it's still labeled work in progress 🙃

**Comment by Rican7** [comment]
Whoops! Sorry about that! I didn't even realize the label. The merge seemed obvious, so I trigger fingered it. Sorry about that. :/

**Pull request merged**
