### PR TITLE
Copy exact timezone from \DateTime object

### PR DESCRIPTION
**Pull request by srsbiz**

### CODE REVIEW

**Comment by koenpunt** [comment]
@jpfuentes2 you have any idea why we've let PHP extract the timezone from the datestring?

**Comment by jpfuentes2** [comment]
@koenpunt Nope, that sounds like a bug.

**Comment by jpfuentes2** [comment]
Thanks for your contribution, @srsbiz. I'd usually ask for a test demonstrating your code change has the desired effect. Thoughts, @koenpunt ?

**Comment by jpfuentes2** [comment]
Test coverage provided in #522 so I'm going to merge.

**Pull request merged**
