### PR TITLE
Add info on skipped tests and how to fix them

### PR DESCRIPTION
**Pull request by louismrose**
I had a few issues getting the test suite to run to completion on my machine, so I've taken the liberty of adding a few notes to the contributors documentation.

If these look reasonable, would it be worth merging them into the main repo?

### CODE REVIEW

**Comment by koenpunt** [comment]
Can you mention the `PHPAR_*` environment variables as well?

**Comment by louismrose** [comment]
Good idea -- done.

**Comment by louismrose** [comment]
Hey @koenpunt. Is there a typical process for merging PRs here? If there's anything else needed for this one or #546, please let me know. We make good use of this library at work, and so we're happy for me to spend a bit of time supporting the project, if that would be useful.

**Comment by koenpunt** [comment]
@louismrose hi, thanks for your contribution! Unfortunately not, which causes PR's to linger for long periods of time.. Especially PR's around (mayor) code changes, like #430, which has been around for ages now..

Anyway, your changes are scoped to OSX (`brew ..` stuff), so if you can make that clear by adding that to your example I'm happy to merge:

>  (e.g., `brew install php56-memcache memcached` for OSX)

**Comment by louismrose** [comment]
@koenpunt Thanks for the clarification: good to know!

I've made the changes you suggest (and [future proofed](http://www.apple.com/macos/) them by referring to the Apple OS as macOS).

**Comment by koenpunt** [comment]
Thanks! 👍

**Pull request merged**
